/*
 * WBOX NT Syscall Name Table
 * Generated from doc/nt.md
 */
#include "syscalls.h"
#include "win32k_syscalls.h"
#include <stdint.h>
#include <string.h>

static const char *nt_syscall_names[NT_SYSCALL_COUNT] = {
    [0]   = "NtAcceptConnectPort",
    [1]   = "NtAccessCheck",
    [2]   = "NtAccessCheckAndAuditAlarm",
    [3]   = "NtAccessCheckByType",
    [4]   = "NtAccessCheckByTypeAndAuditAlarm",
    [5]   = "NtAccessCheckByTypeResultList",
    [6]   = "NtAccessCheckByTypeResultListAndAuditAlarm",
    [7]   = "NtAccessCheckByTypeResultListAndAuditAlarmByHandle",
    [8]   = "NtAddAtom",
    [9]   = "NtAddBootEntry",
    [10]  = "NtAddDriverEntry",
    [11]  = "NtAdjustGroupsToken",
    [12]  = "NtAdjustPrivilegesToken",
    [13]  = "NtAlertResumeThread",
    [14]  = "NtAlertThread",
    [15]  = "NtAllocateLocallyUniqueId",
    [16]  = "NtAllocateUserPhysicalPages",
    [17]  = "NtAllocateUuids",
    [18]  = "NtAllocateVirtualMemory",
    [19]  = "NtApphelpCacheControl",
    [20]  = "NtAreMappedFilesTheSame",
    [21]  = "NtAssignProcessToJobObject",
    [22]  = "NtCallbackReturn",
    [23]  = "NtCancelDeviceWakeupRequest",
    [24]  = "NtCancelIoFile",
    [25]  = "NtCancelTimer",
    [26]  = "NtClearEvent",
    [27]  = "NtClose",
    [28]  = "NtCloseObjectAuditAlarm",
    [29]  = "NtCompactKeys",
    [30]  = "NtCompareTokens",
    [31]  = "NtCompleteConnectPort",
    [32]  = "NtCompressKey",
    [33]  = "NtConnectPort",
    [34]  = "NtContinue",
    [35]  = "NtCreateDebugObject",
    [36]  = "NtCreateDirectoryObject",
    [37]  = "NtCreateEvent",
    [38]  = "NtCreateEventPair",
    [39]  = "NtCreateFile",
    [40]  = "NtCreateIoCompletion",
    [41]  = "NtCreateJobObject",
    [42]  = "NtCreateJobSet",
    [43]  = "NtCreateKey",
    [44]  = "NtCreateMailslotFile",
    [45]  = "NtCreateMutant",
    [46]  = "NtCreateNamedPipeFile",
    [47]  = "NtCreatePagingFile",
    [48]  = "NtCreatePort",
    [49]  = "NtCreateProcess",
    [50]  = "NtCreateProcessEx",
    [51]  = "NtCreateProfile",
    [52]  = "NtCreateSection",
    [53]  = "NtCreateSemaphore",
    [54]  = "NtCreateSymbolicLinkObject",
    [55]  = "NtCreateThread",
    [56]  = "NtCreateTimer",
    [57]  = "NtCreateToken",
    [58]  = "NtCreateWaitablePort",
    [59]  = "NtDebugActiveProcess",
    [60]  = "NtDebugContinue",
    [61]  = "NtDelayExecution",
    [62]  = "NtDeleteAtom",
    [63]  = "NtDeleteBootEntry",
    [64]  = "NtDeleteDriverEntry",
    [65]  = "NtDeleteFile",
    [66]  = "NtDeleteKey",
    [67]  = "NtDeleteObjectAuditAlarm",
    [68]  = "NtDeleteValueKey",
    [69]  = "NtDeviceIoControlFile",
    [70]  = "NtDisplayString",
    [71]  = "NtDuplicateObject",
    [72]  = "NtDuplicateToken",
    [73]  = "NtEnumerateBootEntries",
    [74]  = "NtEnumerateDriverEntries",
    [75]  = "NtEnumerateKey",
    [76]  = "NtEnumerateSystemEnvironmentValuesEx",
    [77]  = "NtEnumerateValueKey",
    [78]  = "NtExtendSection",
    [79]  = "NtFilterToken",
    [80]  = "NtFindAtom",
    [81]  = "NtFlushBuffersFile",
    [82]  = "NtFlushInstructionCache",
    [83]  = "NtFlushKey",
    [84]  = "NtFlushVirtualMemory",
    [85]  = "NtFlushWriteBuffer",
    [86]  = "NtFreeUserPhysicalPages",
    [87]  = "NtFreeVirtualMemory",
    [88]  = "NtFsControlFile",
    [89]  = "NtGetContextThread",
    [90]  = "NtGetDevicePowerState",
    [91]  = "NtGetPlugPlayEvent",
    [92]  = "NtGetWriteWatch",
    [93]  = "NtImpersonateAnonymousToken",
    [94]  = "NtImpersonateClientOfPort",
    [95]  = "NtImpersonateThread",
    [96]  = "NtInitializeRegistry",
    [97]  = "NtInitiatePowerAction",
    [98]  = "NtIsProcessInJob",
    [99]  = "NtIsSystemResumeAutomatic",
    [100] = "NtListenPort",
    [101] = "NtLoadDriver",
    [102] = "NtLoadKey",
    [103] = "NtLoadKey2",
    [104] = "NtLoadKeyEx",
    [105] = "NtLockFile",
    [106] = "NtLockProductActivationKeys",
    [107] = "NtLockRegistryKey",
    [108] = "NtLockVirtualMemory",
    [109] = "NtMakePermanentObject",
    [110] = "NtMakeTemporaryObject",
    [111] = "NtMapUserPhysicalPages",
    [112] = "NtMapUserPhysicalPagesScatter",
    [113] = "NtMapViewOfSection",
    [114] = "NtModifyBootEntry",
    [115] = "NtModifyDriverEntry",
    [116] = "NtNotifyChangeDirectoryFile",
    [117] = "NtNotifyChangeKey",
    [118] = "NtNotifyChangeMultipleKeys",
    [119] = "NtOpenDirectoryObject",
    [120] = "NtOpenEvent",
    [121] = "NtOpenEventPair",
    [122] = "NtOpenFile",
    [123] = "NtOpenIoCompletion",
    [124] = "NtOpenJobObject",
    [125] = "NtOpenKey",
    [126] = "NtOpenMutant",
    [127] = "NtOpenObjectAuditAlarm",
    [128] = "NtOpenProcess",
    [129] = "NtOpenProcessToken",
    [130] = "NtOpenProcessTokenEx",
    [131] = "NtOpenSection",
    [132] = "NtOpenSemaphore",
    [133] = "NtOpenSymbolicLinkObject",
    [134] = "NtOpenThread",
    [135] = "NtOpenThreadToken",
    [136] = "NtOpenThreadTokenEx",
    [137] = "NtOpenTimer",
    [138] = "NtPlugPlayControl",
    [139] = "NtPowerInformation",
    [140] = "NtPrivilegeCheck",
    [141] = "NtPrivilegeObjectAuditAlarm",
    [142] = "NtPrivilegedServiceAuditAlarm",
    [143] = "NtProtectVirtualMemory",
    [144] = "NtPulseEvent",
    [145] = "NtQueryAttributesFile",
    [146] = "NtQueryBootEntryOrder",
    [147] = "NtQueryBootOptions",
    [148] = "NtQueryDebugFilterState",
    [149] = "NtQueryDefaultLocale",
    [150] = "NtQueryDefaultUILanguage",
    [151] = "NtQueryDirectoryFile",
    [152] = "NtQueryDirectoryObject",
    [153] = "NtQueryDriverEntryOrder",
    [154] = "NtQueryEaFile",
    [155] = "NtQueryEvent",
    [156] = "NtQueryFullAttributesFile",
    [157] = "NtQueryInformationAtom",
    [158] = "NtQueryInformationFile",
    [159] = "NtQueryInformationJobObject",
    [160] = "NtQueryInformationPort",
    [161] = "NtQueryInformationProcess",
    [162] = "NtQueryInformationThread",
    [163] = "NtQueryInformationToken",
    [164] = "NtQueryInstallUILanguage",
    [165] = "NtQueryIntervalProfile",
    [166] = "NtQueryIoCompletion",
    [167] = "NtQueryKey",
    [168] = "NtQueryMultipleValueKey",
    [169] = "NtQueryMutant",
    [170] = "NtQueryObject",
    [171] = "NtQueryOpenSubKeys",
    [172] = "NtQueryOpenSubKeysEx",
    [173] = "NtQueryPerformanceCounter",
    [174] = "NtQueryQuotaInformationFile",
    [175] = "NtQuerySection",
    [176] = "NtQuerySecurityObject",
    [177] = "NtQuerySemaphore",
    [178] = "NtQuerySymbolicLinkObject",
    [179] = "NtQuerySystemEnvironmentValue",
    [180] = "NtQuerySystemEnvironmentValueEx",
    [181] = "NtQuerySystemInformation",
    [182] = "NtQuerySystemTime",
    [183] = "NtQueryTimer",
    [184] = "NtQueryTimerResolution",
    [185] = "NtQueryValueKey",
    [186] = "NtQueryVirtualMemory",
    [187] = "NtQueryVolumeInformationFile",
    [188] = "NtQueueApcThread",
    [189] = "NtRaiseException",
    [190] = "NtRaiseHardError",
    [191] = "NtReadFile",
    [192] = "NtReadFileScatter",
    [193] = "NtReadRequestData",
    [194] = "NtReadVirtualMemory",
    [195] = "NtRegisterThreadTerminatePort",
    [196] = "NtReleaseMutant",
    [197] = "NtReleaseSemaphore",
    [198] = "NtRemoveIoCompletion",
    [199] = "NtRemoveProcessDebug",
    [200] = "NtRenameKey",
    [201] = "NtReplaceKey",
    [202] = "NtReplyPort",
    [203] = "NtReplyWaitReceivePort",
    [204] = "NtReplyWaitReceivePortEx",
    [205] = "NtReplyWaitReplyPort",
    [206] = "NtRequestDeviceWakeup",
    [207] = "NtRequestPort",
    [208] = "NtRequestWaitReplyPort",
    [209] = "NtRequestWakeupLatency",
    [210] = "NtResetEvent",
    [211] = "NtResetWriteWatch",
    [212] = "NtRestoreKey",
    [213] = "NtResumeProcess",
    [214] = "NtResumeThread",
    [215] = "NtSaveKey",
    [216] = "NtSaveKeyEx",
    [217] = "NtSaveMergedKeys",
    [218] = "NtSecureConnectPort",
    [219] = "NtSetBootEntryOrder",
    [220] = "NtSetBootOptions",
    [221] = "NtSetContextThread",
    [222] = "NtSetDebugFilterState",
    [223] = "NtSetDefaultHardErrorPort",
    [224] = "NtSetDefaultLocale",
    [225] = "NtSetDefaultUILanguage",
    [226] = "NtSetDriverEntryOrder",
    [227] = "NtSetEaFile",
    [228] = "NtSetEvent",
    [229] = "NtSetEventBoostPriority",
    [230] = "NtSetHighEventPair",
    [231] = "NtSetHighWaitLowEventPair",
    [232] = "NtSetInformationDebugObject",
    [233] = "NtSetInformationFile",
    [234] = "NtSetInformationJobObject",
    [235] = "NtSetInformationKey",
    [236] = "NtSetInformationObject",
    [237] = "NtSetInformationProcess",
    [238] = "NtSetInformationThread",
    [239] = "NtSetInformationToken",
    [240] = "NtSetIntervalProfile",
    [241] = "NtSetIoCompletion",
    [242] = "NtSetLdtEntries",
    [243] = "NtSetLowEventPair",
    [244] = "NtSetLowWaitHighEventPair",
    [245] = "NtSetQuotaInformationFile",
    [246] = "NtSetSecurityObject",
    [247] = "NtSetSystemEnvironmentValue",
    [248] = "NtSetSystemEnvironmentValueEx",
    [249] = "NtSetSystemInformation",
    [250] = "NtSetSystemPowerState",
    [251] = "NtSetSystemTime",
    [252] = "NtSetThreadExecutionState",
    [253] = "NtSetTimer",
    [254] = "NtSetTimerResolution",
    [255] = "NtSetUuidSeed",
    [256] = "NtSetValueKey",
    [257] = "NtSetVolumeInformationFile",
    [258] = "NtShutdownSystem",
    [259] = "NtSignalAndWaitForSingleObject",
    [260] = "NtStartProfile",
    [261] = "NtStopProfile",
    [262] = "NtSuspendProcess",
    [263] = "NtSuspendThread",
    [264] = "NtSystemDebugControl",
    [265] = "NtTerminateJobObject",
    [266] = "NtTerminateProcess",
    [267] = "NtTerminateThread",
    [268] = "NtTestAlert",
    [269] = "NtTraceEvent",
    [270] = "NtTranslateFilePath",
    [271] = "NtUnloadDriver",
    [272] = "NtUnloadKey",
    [273] = "NtUnloadKey2",
    [274] = "NtUnloadKeyEx",
    [275] = "NtUnlockFile",
    [276] = "NtUnlockVirtualMemory",
    [277] = "NtUnmapViewOfSection",
    [278] = "NtVdmControl",
    [279] = "NtWaitForDebugEvent",
    [280] = "NtWaitForMultipleObjects",
    [281] = "NtWaitForSingleObject",
    [282] = "NtWaitHighEventPair",
    [283] = "NtWaitLowEventPair",
    [284] = "NtWriteFile",
    [285] = "NtWriteFileGather",
    [286] = "NtWriteRequestData",
    [287] = "NtWriteVirtualMemory",
    [288] = "NtYieldExecution",
    [289] = "NtCreateKeyedEvent",
    [290] = "NtOpenKeyedEvent",
    [291] = "NtReleaseKeyedEvent",
    [292] = "NtWaitForKeyedEvent",
    [293] = "NtQueryPortInformationProcess",
    [294] = "NtGetCurrentProcessorNumber",
    [295] = "NtWaitForMultipleObjects32",
};

/*
 * Win32k syscall names - sparse array indexed by (syscall_num - WIN32K_SYSCALL_BASE)
 * Only populated entries are shown; uninitialized entries are NULL
 */
static const char *win32k_syscall_names[WIN32K_SYSCALL_COUNT] = {
    /* GDI Syscalls (0-302) */
    [0] = "NtGdiAbortDoc", [1] = "NtGdiAbortPath", [2] = "NtGdiAddFontResourceW",
    [3] = "NtGdiAddRemoteFontToDC", [4] = "NtGdiAddFontMemResourceEx",
    [5] = "NtGdiRemoveMergeFont", [6] = "NtGdiAddRemoteMMInstanceToDC",
    [7] = "NtGdiAlphaBlend", [8] = "NtGdiAngleArc", [9] = "NtGdiAnyLinkedFonts",
    [10] = "NtGdiFontIsLinked", [11] = "NtGdiArcInternal", [12] = "NtGdiBeginPath",
    [13] = "NtGdiBitBlt", [14] = "NtGdiCancelDC", [15] = "NtGdiCheckBitmapBits",
    [16] = "NtGdiCloseFigure", [17] = "NtGdiClearBitmapAttributes",
    [18] = "NtGdiClearBrushAttributes", [19] = "NtGdiColorCorrectPalette",
    [20] = "NtGdiCombineRgn", [21] = "NtGdiCombineTransform",
    [22] = "NtGdiComputeXformCoefficients", [23] = "NtGdiConsoleTextOut",
    [24] = "NtGdiConvertMetafileRect", [25] = "NtGdiCreateBitmap",
    [26] = "NtGdiCreateClientObj", [27] = "NtGdiCreateColorSpace",
    [28] = "NtGdiCreateColorTransform", [29] = "NtGdiCreateCompatibleBitmap",
    [30] = "NtGdiCreateCompatibleDC", [31] = "NtGdiCreateDIBBrush",
    [32] = "NtGdiCreateDIBitmapInternal", [33] = "NtGdiCreateDIBSection",
    [34] = "NtGdiCreateEllipticRgn", [35] = "NtGdiCreateHalftonePalette",
    [36] = "NtGdiCreateHatchBrushInternal", [37] = "NtGdiCreateMetafileDC",
    [38] = "NtGdiCreatePaletteInternal", [39] = "NtGdiCreatePatternBrushInternal",
    [40] = "NtGdiCreatePen", [41] = "NtGdiCreateRectRgn",
    [42] = "NtGdiCreateRoundRectRgn", [43] = "NtGdiCreateServerMetaFile",
    [44] = "NtGdiCreateSolidBrush", [45] = "NtGdiD3dContextCreate",
    [46] = "NtGdiD3dContextDestroy", [47] = "NtGdiD3dContextDestroyAll",
    [48] = "NtGdiD3dValidateTextureStageState", [49] = "NtGdiD3dDrawPrimitives2",
    [50] = "NtGdiDdGetDriverState", [51] = "NtGdiDdAddAttachedSurface",
    [52] = "NtGdiDdAlphaBlt", [53] = "NtGdiDdAttachSurface",
    [54] = "NtGdiDdBeginMoCompFrame", [55] = "NtGdiDdBlt",
    [56] = "NtGdiDdCanCreateSurface", [57] = "NtGdiDdCanCreateD3DBuffer",
    [58] = "NtGdiDdColorControl", [59] = "NtGdiDdCreateDirectDrawObject",
    [60] = "NtGdiDdCreateSurface", [61] = "NtGdiDdCreateD3DBuffer",
    [62] = "NtGdiDdCreateMoComp", [63] = "NtGdiDdCreateSurfaceObject",
    [64] = "NtGdiDdDeleteDirectDrawObject", [65] = "NtGdiDdDeleteSurfaceObject",
    [66] = "NtGdiDdDestroyMoComp", [67] = "NtGdiDdDestroySurface",
    [68] = "NtGdiDdDestroyD3DBuffer", [69] = "NtGdiDdEndMoCompFrame",
    [70] = "NtGdiDdFlip", [71] = "NtGdiDdFlipToGDISurface",
    [72] = "NtGdiDdGetAvailDriverMemory", [73] = "NtGdiDdGetBltStatus",
    [74] = "NtGdiDdGetDC", [75] = "NtGdiDdGetDriverInfo",
    [76] = "NtGdiDdGetDxHandle", [77] = "NtGdiDdGetFlipStatus",
    [78] = "NtGdiDdGetInternalMoCompInfo", [79] = "NtGdiDdGetMoCompBuffInfo",
    [80] = "NtGdiDdGetMoCompGuids", [81] = "NtGdiDdGetMoCompFormats",
    [82] = "NtGdiDdGetScanLine", [83] = "NtGdiDdLock", [84] = "NtGdiDdLockD3D",
    [85] = "NtGdiDdQueryDirectDrawObject", [86] = "NtGdiDdQueryMoCompStatus",
    [87] = "NtGdiDdReenableDirectDrawObject", [88] = "NtGdiDdReleaseDC",
    [89] = "NtGdiDdRenderMoComp", [90] = "NtGdiDdResetVisrgn",
    [91] = "NtGdiDdSetColorKey", [92] = "NtGdiDdSetExclusiveMode",
    [93] = "NtGdiDdSetGammaRamp", [94] = "NtGdiDdCreateSurfaceEx",
    [95] = "NtGdiDdSetOverlayPosition", [96] = "NtGdiDdUnattachSurface",
    [97] = "NtGdiDdUnlock", [98] = "NtGdiDdUnlockD3D",
    [99] = "NtGdiDdUpdateOverlay", [100] = "NtGdiDdWaitForVerticalBlank",
    [101] = "NtGdiDvpCanCreateVideoPort", [102] = "NtGdiDvpColorControl",
    [103] = "NtGdiDvpCreateVideoPort", [104] = "NtGdiDvpDestroyVideoPort",
    [105] = "NtGdiDvpFlipVideoPort", [106] = "NtGdiDvpGetVideoPortBandwidth",
    [107] = "NtGdiDvpGetVideoPortField", [108] = "NtGdiDvpGetVideoPortFlipStatus",
    [109] = "NtGdiDvpGetVideoPortInputFormats", [110] = "NtGdiDvpGetVideoPortLine",
    [111] = "NtGdiDvpGetVideoPortOutputFormats", [112] = "NtGdiDvpGetVideoPortConnectInfo",
    [113] = "NtGdiDvpGetVideoSignalStatus", [114] = "NtGdiDvpUpdateVideoPort",
    [115] = "NtGdiDvpWaitForVideoPortSync", [116] = "NtGdiDvpAcquireNotification",
    [117] = "NtGdiDvpReleaseNotification", [118] = "NtGdiDxgGenericThunk",
    [119] = "NtGdiDeleteClientObj", [120] = "NtGdiDeleteColorSpace",
    [121] = "NtGdiDeleteColorTransform", [122] = "NtGdiDeleteObjectApp",
    [123] = "NtGdiDescribePixelFormat", [124] = "NtGdiGetPerBandInfo",
    [125] = "NtGdiDoBanding", [126] = "NtGdiDoPalette", [127] = "NtGdiDrawEscape",
    [128] = "NtGdiEllipse", [129] = "NtGdiEnableEudc", [130] = "NtGdiEndDoc",
    [131] = "NtGdiEndPage", [132] = "NtGdiEndPath", [133] = "NtGdiEnumFontChunk",
    [134] = "NtGdiEnumFontClose", [135] = "NtGdiEnumFontOpen",
    [136] = "NtGdiEnumObjects", [137] = "NtGdiEqualRgn",
    [138] = "NtGdiEudcLoadUnloadLink", [139] = "NtGdiExcludeClipRect",
    [140] = "NtGdiExtCreatePen", [141] = "NtGdiExtCreateRegion",
    [142] = "NtGdiExtEscape", [143] = "NtGdiExtFloodFill",
    [144] = "NtGdiExtGetObjectW", [145] = "NtGdiExtSelectClipRgn",
    [146] = "NtGdiExtTextOutW", [147] = "NtGdiFillPath", [148] = "NtGdiFillRgn",
    [149] = "NtGdiFlattenPath", [150] = "NtGdiFlush", [151] = "NtGdiForceUFIMapping",
    [152] = "NtGdiFrameRgn", [153] = "NtGdiFullscreenControl",
    [154] = "NtGdiGetAndSetDCDword", [155] = "NtGdiGetAppClipBox",
    [156] = "NtGdiGetBitmapBits", [157] = "NtGdiGetBitmapDimension",
    [158] = "NtGdiGetBoundsRect", [159] = "NtGdiGetCharABCWidthsW",
    [160] = "NtGdiGetCharacterPlacementW", [161] = "NtGdiGetCharSet",
    [162] = "NtGdiGetCharWidthW", [163] = "NtGdiGetCharWidthInfo",
    [164] = "NtGdiGetColorAdjustment", [165] = "NtGdiGetColorSpaceforBitmap",
    [166] = "NtGdiGetDCDword", [167] = "NtGdiGetDCforBitmap",
    [168] = "NtGdiGetDCObject", [169] = "NtGdiGetDCPoint",
    [170] = "NtGdiGetDeviceCaps", [171] = "NtGdiGetDeviceGammaRamp",
    [172] = "NtGdiGetDeviceCapsAll", [173] = "NtGdiGetDIBitsInternal",
    [174] = "NtGdiGetETM", [175] = "NtGdiGetEudcTimeStampEx",
    [176] = "NtGdiGetFontData", [177] = "NtGdiGetFontResourceInfoInternalW",
    [178] = "NtGdiGetGlyphIndicesW", [179] = "NtGdiGetGlyphIndicesWInternal",
    [180] = "NtGdiGetGlyphOutline", [181] = "NtGdiGetKerningPairs",
    [182] = "NtGdiGetLinkedUFIs", [183] = "NtGdiGetMiterLimit",
    [184] = "NtGdiGetMonitorID", [185] = "NtGdiGetNearestColor",
    [186] = "NtGdiGetNearestPaletteIndex", [187] = "NtGdiGetObjectBitmapHandle",
    [188] = "NtGdiGetOutlineTextMetricsInternalW", [189] = "NtGdiGetPath",
    [190] = "NtGdiGetPixel", [191] = "NtGdiGetRandomRgn",
    [192] = "NtGdiGetRasterizerCaps", [193] = "NtGdiGetRealizationInfo",
    [194] = "NtGdiGetRegionData", [195] = "NtGdiGetRgnBox",
    [196] = "NtGdiGetServerMetaFileBits", [197] = "NtGdiGetSpoolMessage",
    [198] = "NtGdiGetStats", [199] = "NtGdiGetStockObject",
    [200] = "NtGdiGetStringBitmapW", [201] = "NtGdiGetSystemPaletteUse",
    [202] = "NtGdiGetTextCharsetInfo", [203] = "NtGdiGetTextExtent",
    [204] = "NtGdiGetTextExtentExW", [205] = "NtGdiGetTextFaceW",
    [206] = "NtGdiGetTextMetricsW", [207] = "NtGdiGetTransform",
    [208] = "NtGdiGetUFI", [209] = "NtGdiGetEmbUFI", [210] = "NtGdiGetUFIPathname",
    [211] = "NtGdiGetEmbedFonts", [212] = "NtGdiChangeGhostFont",
    [213] = "NtGdiAddEmbFontToDC", [214] = "NtGdiGetFontUnicodeRanges",
    [215] = "NtGdiGetWidthTable", [216] = "NtGdiGradientFill",
    [217] = "NtGdiHfontCreate", [218] = "NtGdiIcmBrushInfo", [219] = "NtGdiInit",
    [220] = "NtGdiInitSpool", [221] = "NtGdiIntersectClipRect",
    [222] = "NtGdiInvertRgn", [223] = "NtGdiLineTo", [224] = "NtGdiMakeFontDir",
    [225] = "NtGdiMakeInfoDC", [226] = "NtGdiMaskBlt",
    [227] = "NtGdiModifyWorldTransform", [228] = "NtGdiMonoBitmap",
    [229] = "NtGdiMoveTo", [230] = "NtGdiOffsetClipRgn", [231] = "NtGdiOffsetRgn",
    [232] = "NtGdiOpenDCW", [233] = "NtGdiPatBlt", [234] = "NtGdiPolyPatBlt",
    [235] = "NtGdiPathToRegion", [236] = "NtGdiPlgBlt", [237] = "NtGdiPolyDraw",
    [238] = "NtGdiPolyPolyDraw", [239] = "NtGdiPolyTextOutW",
    [240] = "NtGdiPtInRegion", [241] = "NtGdiPtVisible", [242] = "NtGdiQueryFonts",
    [243] = "NtGdiQueryFontAssocInfo", [244] = "NtGdiRectangle",
    [245] = "NtGdiRectInRegion", [246] = "NtGdiRectVisible",
    [247] = "NtGdiRemoveFontResourceW", [248] = "NtGdiRemoveFontMemResourceEx",
    [249] = "NtGdiResetDC", [250] = "NtGdiResizePalette", [251] = "NtGdiRestoreDC",
    [252] = "NtGdiRoundRect", [253] = "NtGdiSaveDC", [254] = "NtGdiScaleViewportExtEx",
    [255] = "NtGdiScaleWindowExtEx", [256] = "NtGdiSelectBitmap",
    [257] = "NtGdiSelectBrush", [258] = "NtGdiSelectClipPath",
    [259] = "NtGdiSelectFont", [260] = "NtGdiSelectPen",
    [261] = "NtGdiSetBitmapAttributes", [262] = "NtGdiSetBitmapBits",
    [263] = "NtGdiSetBitmapDimension", [264] = "NtGdiSetBoundsRect",
    [265] = "NtGdiSetBrushAttributes", [266] = "NtGdiSetBrushOrg",
    [267] = "NtGdiSetColorAdjustment", [268] = "NtGdiSetColorSpace",
    [269] = "NtGdiSetDeviceGammaRamp", [270] = "NtGdiSetDIBitsToDeviceInternal",
    [271] = "NtGdiSetFontEnumeration", [272] = "NtGdiSetFontXform",
    [273] = "NtGdiSetIcmMode", [274] = "NtGdiSetLinkedUFIs",
    [275] = "NtGdiSetMagicColors", [276] = "NtGdiSetMetaRgn",
    [277] = "NtGdiSetMiterLimit", [278] = "NtGdiGetDeviceWidth",
    [279] = "NtGdiMirrorWindowOrg", [280] = "NtGdiSetLayout", [281] = "NtGdiSetPixel",
    [282] = "NtGdiSetPixelFormat", [283] = "NtGdiSetRectRgn",
    [284] = "NtGdiSetSystemPaletteUse", [285] = "NtGdiSetTextJustification",
    [286] = "NtGdiSetupPublicCFONT", [287] = "NtGdiSetVirtualResolution",
    [288] = "NtGdiSetSizeDevice", [289] = "NtGdiStartDoc", [290] = "NtGdiStartPage",
    [291] = "NtGdiStretchBlt", [292] = "NtGdiStretchDIBitsInternal",
    [293] = "NtGdiStrokeAndFillPath", [294] = "NtGdiStrokePath",
    [295] = "NtGdiSwapBuffers", [296] = "NtGdiTransformPoints",
    [297] = "NtGdiTransparentBlt", [298] = "NtGdiUnloadPrinterDriver",
    [299] = "NtGdiUnmapMemFont", [300] = "NtGdiUnrealizeObject",
    [301] = "NtGdiUpdateColors", [302] = "NtGdiWidenPath",
    /* User Syscalls (309-603) */
    [309] = "NtUserActivateKeyboardLayout", [310] = "NtUserAlterWindowStyle",
    [311] = "NtUserAssociateInputContext", [312] = "NtUserAttachThreadInput",
    [313] = "NtUserBeginPaint", [314] = "NtUserBitBltSysBmp",
    [315] = "NtUserBlockInput", [316] = "NtUserBuildHimcList",
    [317] = "NtUserBuildHwndList", [318] = "NtUserBuildNameList",
    [319] = "NtUserBuildPropList", [320] = "NtUserCallHwnd",
    [321] = "NtUserCallHwndLock", [322] = "NtUserCallHwndOpt",
    [323] = "NtUserCallHwndParam", [324] = "NtUserCallHwndParamLock",
    [325] = "NtUserCallMsgFilter", [326] = "NtUserCallNextHookEx",
    [327] = "NtUserCallNoParam", [328] = "NtUserCallOneParam",
    [329] = "NtUserCallTwoParam", [330] = "NtUserChangeClipboardChain",
    [331] = "NtUserChangeDisplaySettings", [332] = "NtUserCheckImeHotKey",
    [333] = "NtUserCheckMenuItem", [334] = "NtUserChildWindowFromPointEx",
    [335] = "NtUserClipCursor", [336] = "NtUserCloseClipboard",
    [337] = "NtUserCloseDesktop", [338] = "NtUserCloseWindowStation",
    [339] = "NtUserConsoleControl", [340] = "NtUserConvertMemHandle",
    [341] = "NtUserCopyAcceleratorTable", [342] = "NtUserCountClipboardFormats",
    [343] = "NtUserCreateAcceleratorTable", [344] = "NtUserCreateCaret",
    [345] = "NtUserCreateDesktop", [346] = "NtUserCreateInputContext",
    [347] = "NtUserCreateLocalMemHandle", [348] = "NtUserCreateWindowEx",
    [349] = "NtUserCreateWindowStation", [350] = "NtUserDdeGetQualityOfService",
    [351] = "NtUserDdeInitialize", [352] = "NtUserDdeSetQualityOfService",
    [353] = "NtUserDeferWindowPos", [354] = "NtUserDefSetText",
    [355] = "NtUserDeleteMenu", [356] = "NtUserDestroyAcceleratorTable",
    [357] = "NtUserDestroyCursor", [358] = "NtUserDestroyInputContext",
    [359] = "NtUserDestroyMenu", [360] = "NtUserDestroyWindow",
    [361] = "NtUserDisableThreadIme", [362] = "NtUserDispatchMessage",
    [363] = "NtUserDragDetect", [364] = "NtUserDragObject",
    [365] = "NtUserDrawAnimatedRects", [366] = "NtUserDrawCaption",
    [367] = "NtUserDrawCaptionTemp", [368] = "NtUserDrawIconEx",
    [369] = "NtUserDrawMenuBarTemp", [370] = "NtUserEmptyClipboard",
    [371] = "NtUserEnableMenuItem", [372] = "NtUserEnableScrollBar",
    [373] = "NtUserEndDeferWindowPosEx", [374] = "NtUserEndMenu",
    [375] = "NtUserEndPaint", [376] = "NtUserEnumDisplayDevices",
    [377] = "NtUserEnumDisplayMonitors", [378] = "NtUserEnumDisplaySettings",
    [379] = "NtUserEvent", [380] = "NtUserExcludeUpdateRgn",
    [381] = "NtUserFillWindow", [382] = "NtUserFindExistingCursorIcon",
    [383] = "NtUserFindWindowEx", [384] = "NtUserFlashWindowEx",
    [385] = "NtUserGetAltTabInfo", [386] = "NtUserGetAncestor",
    [387] = "NtUserGetAppImeLevel", [388] = "NtUserGetAsyncKeyState",
    [389] = "NtUserGetAtomName", [390] = "NtUserGetCaretBlinkTime",
    [391] = "NtUserGetCaretPos", [392] = "NtUserGetClassInfo",
    [393] = "NtUserGetClassName", [394] = "NtUserGetClipboardData",
    [395] = "NtUserGetClipboardFormatName", [396] = "NtUserGetClipboardOwner",
    [397] = "NtUserGetClipboardSequenceNumber", [398] = "NtUserGetClipboardViewer",
    [399] = "NtUserGetClipCursor", [400] = "NtUserGetComboBoxInfo",
    [401] = "NtUserGetControlBrush", [402] = "NtUserGetControlColor",
    [403] = "NtUserGetCPD", [404] = "NtUserGetCursorFrameInfo",
    [405] = "NtUserGetCursorInfo", [406] = "NtUserGetDC", [407] = "NtUserGetDCEx",
    [408] = "NtUserGetDoubleClickTime", [409] = "NtUserGetForegroundWindow",
    [410] = "NtUserGetGuiResources", [411] = "NtUserGetGUIThreadInfo",
    [412] = "NtUserGetIconInfo", [413] = "NtUserGetIconSize",
    [414] = "NtUserGetImeHotKey", [415] = "NtUserGetImeInfoEx",
    [416] = "NtUserGetInternalWindowPos", [417] = "NtUserGetKeyboardLayoutList",
    [418] = "NtUserGetKeyboardLayoutName", [419] = "NtUserGetKeyboardState",
    [420] = "NtUserGetKeyNameText", [421] = "NtUserGetKeyState",
    [422] = "NtUserGetListBoxInfo", [423] = "NtUserGetMenuBarInfo",
    [424] = "NtUserGetMenuIndex", [425] = "NtUserGetMenuItemRect",
    [426] = "NtUserGetMessage", [427] = "NtUserGetMouseMovePointsEx",
    [428] = "NtUserGetObjectInformation", [429] = "NtUserGetOpenClipboardWindow",
    [430] = "NtUserGetPriorityClipboardFormat", [431] = "NtUserGetProcessWindowStation",
    [432] = "NtUserGetRawInputBuffer", [433] = "NtUserGetRawInputData",
    [434] = "NtUserGetRawInputDeviceInfo", [435] = "NtUserGetRawInputDeviceList",
    [436] = "NtUserGetRegisteredRawInputDevices", [437] = "NtUserGetScrollBarInfo",
    [438] = "NtUserGetSystemMenu", [439] = "NtUserGetThreadDesktop",
    [440] = "NtUserGetThreadState", [441] = "NtUserGetTitleBarInfo",
    [442] = "NtUserGetUpdateRect", [443] = "NtUserGetUpdateRgn",
    [444] = "NtUserGetWindowDC", [445] = "NtUserGetWindowPlacement",
    [446] = "NtUserGetWOWClass", [447] = "NtUserHardErrorControl",
    [448] = "NtUserHideCaret", [449] = "NtUserHiliteMenuItem",
    [450] = "NtUserImpersonateDdeClientWindow", [451] = "NtUserInitialize",
    [452] = "NtUserInitializeClientPfnArrays", [453] = "NtUserInitTask",
    [454] = "NtUserInternalGetWindowText", [455] = "NtUserInvalidateRect",
    [456] = "NtUserInvalidateRgn", [457] = "NtUserIsClipboardFormatAvailable",
    [458] = "NtUserKillTimer", [459] = "NtUserLoadKeyboardLayoutEx",
    [460] = "NtUserLockWindowStation", [461] = "NtUserLockWindowUpdate",
    [462] = "NtUserLockWorkStation", [463] = "NtUserMapVirtualKeyEx",
    [464] = "NtUserMenuItemFromPoint", [465] = "NtUserMessageCall",
    [466] = "NtUserMinMaximize", [467] = "NtUserMNDragLeave",
    [468] = "NtUserMNDragOver", [469] = "NtUserModifyUserStartupInfoFlags",
    [470] = "NtUserMoveWindow", [471] = "NtUserNotifyIMEStatus",
    [472] = "NtUserNotifyProcessCreate", [473] = "NtUserNotifyWinEvent",
    [474] = "NtUserOpenClipboard", [475] = "NtUserOpenDesktop",
    [476] = "NtUserOpenInputDesktop", [477] = "NtUserOpenWindowStation",
    [478] = "NtUserPaintDesktop", [479] = "NtUserPeekMessage",
    [480] = "NtUserPostMessage", [481] = "NtUserPostThreadMessage",
    [482] = "NtUserPrintWindow", [483] = "NtUserProcessConnect",
    [484] = "NtUserQueryInformationThread", [485] = "NtUserQueryInputContext",
    [486] = "NtUserQuerySendMessage", [487] = "NtUserQueryWindow",
    [488] = "NtUserRealChildWindowFromPoint", [489] = "NtUserRealInternalGetMessage",
    [490] = "NtUserRealWaitMessageEx", [491] = "NtUserRedrawWindow",
    [492] = "NtUserRegisterClassExWOW", [493] = "NtUserRegisterUserApiHook",
    [494] = "NtUserRegisterHotKey", [495] = "NtUserRegisterRawInputDevices",
    [496] = "NtUserRegisterTasklist", [497] = "NtUserRegisterWindowMessage",
    [498] = "NtUserRemoveMenu", [499] = "NtUserRemoveProp",
    [500] = "NtUserResolveDesktop", [501] = "NtUserResolveDesktopForWOW",
    [502] = "NtUserSBGetParms", [503] = "NtUserScrollDC",
    [504] = "NtUserScrollWindowEx", [505] = "NtUserSelectPalette",
    [506] = "NtUserSendInput", [507] = "NtUserSetActiveWindow",
    [508] = "NtUserSetAppImeLevel", [509] = "NtUserSetCapture",
    [510] = "NtUserSetClassLong", [511] = "NtUserSetClassWord",
    [512] = "NtUserSetClipboardData", [513] = "NtUserSetClipboardViewer",
    [514] = "NtUserSetConsoleReserveKeys", [515] = "NtUserSetCursor",
    [516] = "NtUserSetCursorContents", [517] = "NtUserSetCursorIconData",
    [518] = "NtUserSetFocus", [519] = "NtUserSetImeHotKey",
    [520] = "NtUserSetImeInfoEx", [521] = "NtUserSetImeOwnerWindow",
    [522] = "NtUserSetInformationProcess", [523] = "NtUserSetInformationThread",
    [524] = "NtUserSetInternalWindowPos", [525] = "NtUserSetKeyboardState",
    [526] = "NtUserSetLogonNotifyWindow", [527] = "NtUserSetMenu",
    [528] = "NtUserSetMenuContextHelpId", [529] = "NtUserSetMenuDefaultItem",
    [530] = "NtUserSetMenuFlagRtoL", [531] = "NtUserSetObjectInformation",
    [532] = "NtUserSetParent", [533] = "NtUserSetProcessWindowStation",
    [534] = "NtUserSetProp", [535] = "NtUserSetScrollInfo",
    [536] = "NtUserSetShellWindowEx", [537] = "NtUserSetSysColors",
    [538] = "NtUserSetSystemCursor", [539] = "NtUserSetSystemMenu",
    [540] = "NtUserSetSystemTimer", [541] = "NtUserSetThreadDesktop",
    [542] = "NtUserSetThreadLayoutHandles", [543] = "NtUserSetThreadState",
    [544] = "NtUserSetTimer", [545] = "NtUserSetWindowFNID",
    [546] = "NtUserSetWindowLong", [547] = "NtUserSetWindowPlacement",
    [548] = "NtUserSetWindowPos", [549] = "NtUserSetWindowRgn",
    [550] = "NtUserSetWindowsHookAW", [551] = "NtUserSetWindowsHookEx",
    [552] = "NtUserSetWindowStationUser", [553] = "NtUserSetWindowWord",
    [554] = "NtUserSetWinEventHook", [555] = "NtUserShowCaret",
    [556] = "NtUserShowScrollBar", [557] = "NtUserShowWindow",
    [558] = "NtUserShowWindowAsync", [559] = "NtUserSoundSentry",
    [560] = "NtUserSwitchDesktop", [561] = "NtUserSystemParametersInfo",
    [562] = "NtUserTestForInteractiveUser", [563] = "NtUserThunkedMenuInfo",
    [564] = "NtUserThunkedMenuItemInfo", [565] = "NtUserToUnicodeEx",
    [566] = "NtUserTrackMouseEvent", [567] = "NtUserTrackPopupMenuEx",
    [568] = "NtUserCalcMenuBar", [569] = "NtUserPaintMenuBar",
    [570] = "NtUserTranslateAccelerator", [571] = "NtUserTranslateMessage",
    [572] = "NtUserUnhookWindowsHookEx", [573] = "NtUserUnhookWinEvent",
    [574] = "NtUserUnloadKeyboardLayout", [575] = "NtUserUnlockWindowStation",
    [576] = "NtUserUnregisterClass", [577] = "NtUserUnregisterUserApiHook",
    [578] = "NtUserUnregisterHotKey", [579] = "NtUserUpdateInputContext",
    [580] = "NtUserUpdateInstance", [581] = "NtUserUpdateLayeredWindow",
    [582] = "NtUserGetLayeredWindowAttributes", [583] = "NtUserSetLayeredWindowAttributes",
    [584] = "NtUserUpdatePerUserSystemParameters", [585] = "NtUserUserHandleGrantAccess",
    [586] = "NtUserValidateHandleSecure", [587] = "NtUserValidateRect",
    [588] = "NtUserValidateTimerCallback", [589] = "NtUserVkKeyScanEx",
    [590] = "NtUserWaitForInputIdle", [591] = "NtUserWaitForMsgAndEvent",
    [592] = "NtUserWaitMessage", [593] = "NtUserWin32PoolAllocationStats",
    [594] = "NtUserWindowFromPoint", [595] = "NtUserYieldTask",
    [596] = "NtUserRemoteConnect", [597] = "NtUserRemoteRedrawRectangle",
    [598] = "NtUserRemoteRedrawScreen", [599] = "NtUserRemoteStopScreenUpdates",
    [600] = "NtUserCtxDisplayIOCtl",
    /* Engine/DDI Syscalls (604-740) */
    [604] = "NtGdiEngAssociateSurface", [605] = "NtGdiEngCreateBitmap",
    [606] = "NtGdiEngCreateDeviceSurface", [607] = "NtGdiEngCreateDeviceBitmap",
    [608] = "NtGdiEngCreatePalette", [609] = "NtGdiEngComputeGlyphSet",
    [610] = "NtGdiEngCopyBits", [611] = "NtGdiEngDeletePalette",
    [612] = "NtGdiEngDeleteSurface", [613] = "NtGdiEngEraseSurface",
    [614] = "NtGdiEngUnlockSurface", [615] = "NtGdiEngLockSurface",
    [616] = "NtGdiEngBitBlt", [617] = "NtGdiEngStretchBlt",
    [618] = "NtGdiEngPlgBlt", [619] = "NtGdiEngMarkBandingSurface",
    [620] = "NtGdiEngStrokePath", [621] = "NtGdiEngFillPath",
    [622] = "NtGdiEngStrokeAndFillPath", [623] = "NtGdiEngPaint",
    [624] = "NtGdiEngLineTo", [625] = "NtGdiEngAlphaBlend",
    [626] = "NtGdiEngGradientFill", [627] = "NtGdiEngTransparentBlt",
    [628] = "NtGdiEngTextOut", [629] = "NtGdiEngStretchBltROP",
    [630] = "NtGdiXLATEOBJ_cGetPalette", [631] = "NtGdiXLATEOBJ_iXlate",
    [632] = "NtGdiXLATEOBJ_hGetColorTransform", [633] = "NtGdiCLIPOBJ_bEnum",
    [634] = "NtGdiCLIPOBJ_cEnumStart", [635] = "NtGdiCLIPOBJ_ppoGetPath",
    [636] = "NtGdiEngDeletePath", [637] = "NtGdiEngCreateClip",
    [638] = "NtGdiEngDeleteClip", [639] = "NtGdiBRUSHOBJ_ulGetBrushColor",
    [640] = "NtGdiBRUSHOBJ_pvAllocRbrush", [641] = "NtGdiBRUSHOBJ_pvGetRbrush",
    [642] = "NtGdiBRUSHOBJ_hGetColorTransform", [643] = "NtGdiXFORMOBJ_bApplyXform",
    [644] = "NtGdiXFORMOBJ_iGetXform", [645] = "NtGdiFONTOBJ_vGetInfo",
    [646] = "NtGdiFONTOBJ_pxoGetXform", [647] = "NtGdiFONTOBJ_cGetGlyphs",
    [648] = "NtGdiFONTOBJ_pifi", [649] = "NtGdiFONTOBJ_pfdg",
    [650] = "NtGdiFONTOBJ_pQueryGlyphAttrs", [651] = "NtGdiFONTOBJ_pvTrueTypeFontFile",
    [652] = "NtGdiFONTOBJ_cGetAllGlyphHandles", [653] = "NtGdiSTROBJ_bEnum",
    [654] = "NtGdiSTROBJ_bEnumPositionsOnly", [655] = "NtGdiSTROBJ_bGetAdvanceWidths",
    [656] = "NtGdiSTROBJ_vEnumStart", [657] = "NtGdiSTROBJ_dwGetCodePage",
    [658] = "NtGdiPATHOBJ_vGetBounds", [659] = "NtGdiPATHOBJ_bEnum",
    [660] = "NtGdiPATHOBJ_vEnumStart", [661] = "NtGdiPATHOBJ_vEnumStartClipLines",
    [662] = "NtGdiPATHOBJ_bEnumClipLines", [663] = "NtGdiGetDhpdev",
    [664] = "NtGdiEngCheckAbort", [665] = "NtGdiHT_Get8BPPFormatPalette",
    [666] = "NtGdiHT_Get8BPPMaskPalette", [667] = "NtGdiUpdateTransform",
    [668] = "NtGdiSetPUMPDOBJ", [669] = "NtGdiBRUSHOBJ_DeleteRbrush",
    [670] = "NtGdiUMPDEngFreeUserMem", [671] = "NtGdiDrawStream",
    [672] = "NtGdiMakeObjectXferable", [673] = "NtDxEngGetRedirectionBitmap",
    [674] = "NtGdiSetViewportOrgEx", [675] = "NtGdiSetWindowOrgEx",
    [676] = "NtGdiGetFontFamilyInfo", [677] = "NtGdiOffsetViewportOrgEx",
    [678] = "NtGdiOffsetWindowOrgEx", [679] = "NtUserGetMonitorInfo",
    [680] = "NtUserMonitorFromPoint", [681] = "NtUserMonitorFromRect",
    [682] = "NtUserMonitorFromWindow", [683] = "NtUserSetScrollBarInfo",
    [684] = "NtGdiDdDDICreateDCFromMemory", [685] = "NtGdiDdDDIDestroyDCFromMemory",
    [686] = "NtGdiDdDDICheckExclusiveOwnership", [687] = "NtGdiDdDDICreateAllocation",
    [688] = "NtGdiDdDDICheckMonitorPowerState", [689] = "NtGdiDdDDICheckOcclusion",
    [690] = "NtGdiDdDDICloseAdapter", [691] = "NtGdiDdDDICreateContext",
    [692] = "NtGdiDdDDICreateDevice", [693] = "NtGdiDdDDICreateOverlay",
    [694] = "NtGdiDdDDICreateSynchronizationObject", [695] = "NtGdiDdDDIWaitForVerticalBlankEvent",
    [696] = "NtGdiDdDDIWaitForIdle", [697] = "NtGdiDdDDIUpdateOverlay",
    [698] = "NtGdiDdDDIUnlock", [699] = "NtGdiDdDDIDestroyAllocation",
    [700] = "NtGdiDdDDIDestroyContext", [701] = "NtGdiDdDDIDestroyDevice",
    [702] = "NtGdiDdDDIDestroyOverlay", [703] = "NtGdiDdDDIDestroySynchronizationObject",
    [704] = "NtGdiDdDDIEscape", [705] = "NtGdiDdDDIFlipOverlay",
    [706] = "NtGdiDdDDIGetContextSchedulingPriority", [707] = "NtGdiDdDDIGetDeviceState",
    [708] = "NtGdiDdDDIGetDisplayModeList", [709] = "NtGdiDdDDIGetMultisampleMethodList",
    [710] = "NtGdiDdDDIGetPresentHistory", [711] = "NtGdiDdDDIGetProcessSchedulingPriorityClass",
    [712] = "NtGdiDdDDIGetRuntimeData", [713] = "NtGdiDdDDIGetScanLine",
    [714] = "NtGdiDdDDIGetSharedPrimaryHandle", [715] = "NtGdiDdDDIInvalidateActiveVidPn",
    [716] = "NtGdiDdDDILock", [717] = "NtGdiDdDDIOpenAdapterFromDeviceName",
    [718] = "NtGdiDdDDIOpenAdapterFromGdiDisplayName", [719] = "NtGdiDdDDIOpenAdapterFromHdc",
    [720] = "NtGdiDdDDIOpenResource", [721] = "NtGdiDdDDIPollDisplayChildren",
    [722] = "NtGdiDdDDIPresent", [723] = "NtGdiDdDDIQueryAdapterInfo",
    [724] = "NtGdiDdDDIQueryAllocationResidency", [725] = "NtGdiDdDDIQueryResourceInfo",
    [726] = "NtGdiDdDDIQueryStatistics", [727] = "NtGdiDdDDIReleaseProcessVidPnSourceOwners",
    [728] = "NtGdiDdDDIRender", [729] = "NtGdiDdDDISetAllocationPriority",
    [730] = "NtGdiDdDDISetContextSchedulingPriority", [731] = "NtGdiDdDDISetDisplayMode",
    [732] = "NtGdiDdDDISetDisplayPrivateDriverFormat", [733] = "NtGdiDdDDISetGammaRamp",
    [734] = "NtGdiDdDDISetProcessSchedulingPriorityClass", [735] = "NtGdiDdDDISetQueuedLimit",
    [736] = "NtGdiDdDDISetVidPnSourceOwner", [737] = "NtGdiDdDDISharedPrimaryLockNotification",
    [738] = "NtGdiDdDDISharedPrimaryUnLockNotification", [739] = "NtGdiDdDDISignalSynchronizationObject",
    [740] = "NtGdiDdDDIWaitForSynchronizationObject",
};

const char *syscall_get_name(uint32_t num)
{
    if (num < NT_SYSCALL_COUNT) {
        return nt_syscall_names[num];
    }
    if (num >= WIN32K_SYSCALL_BASE) {
        uint32_t idx = num - WIN32K_SYSCALL_BASE;
        if (idx < WIN32K_SYSCALL_COUNT && win32k_syscall_names[idx]) {
            return win32k_syscall_names[idx];
        }
        return "Win32k (unknown)";
    }
    return "Unknown";
}
